[package]
name = "discord_bot"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.5"
shadow-rs = "0.17.1"

[build-dependencies]
shadow-rs = "0.17.1"
